/* eslint-disable no-unused-vars */
export const enum Languages {
  UA = "UA",
  RU = "RU",
}

export enum Props {
  AboutCourse = "AboutCourse",
  AboutUs = "AboutUs",
  Tariffs = "Tariffs",
  HeadingH1First = "HeadingH1First",
  HeadingH1Second = "HeadingH1Second",
  SubHeadingH1First = "SubHeadingH1First",
  SubHeadingH1Second = "SubHeadingH1Second",
  StartLearning = "StartLearning",
  HeadingForWhomeTraining = "HeadingForWhomeTraining",
  Reason1 = "Reason1",
  Reason2 = "Reason2",
  Reason3 = "Reason3",
  HeadingAfterTrainingYouWillBeAble = "HeadingAfterTrainingYouWillBeAble",
  WhatWillBeAble1First = "WhatWillBeAble1First",
  WhatWillBeAble1Second = "WhatWillBeAble1Second",
  WhatWillBeAble2First = "WhatWillBeAble2First",
  WhatWillBeAble2Second = "WhatWillBeAble2Second",
  WhatWillBeAble3First = "WhatWillBeAble3First",
  WhatWillBeAble3Second = "WhatWillBeAble3Second",
  WhatWillBeAble4First = "WhatWillBeAble4First",
  WhatWillBeAble4Second = "WhatWillBeAble4Second",
  WhatWillBeAble5First = "WhatWillBeAble5First",
  WhatWillBeAble5Second = "WhatWillBeAble5Second",
  WhatWillBeAble6First = "WhatWillBeAble6First",
  WhatWillBeAble6Second = "WhatWillBeAble6Second",
  CourseProgram = "CourseProgram",
  Format = "Format",
  Language = "Language",
  Level = "Level",
  Grammar = "Grammar",
  Sets = "Sets",
  Result = "Result",
  Tools = "Tools",
  Textbook = "Textbook",
  TutorialWithTeacher = "TutorialWithTeacher",
  TutorialWithZlata = "TutorialWithZlata",
  English = "English",
  French = "French",
  Deutsch = "Deutsch",
  A1A2 = "A1A2",
  B1 = "B1",
  B2 = "B2",
  Сheckout = "Сheckout",
  ChooseTariff = "ChooseTariff",
  ZlataBochkareva = "ZlataBochkareva",
  Morethan4years = "Morethan4years",
  Over55students = "Over55students",
  AboutUs1 = "AboutUs1",
  AboutUs2 = "AboutUs2",
  AboutUs3 = "AboutUs3",
  AboutUs4 = "AboutUs4",
  AboutGoalOfProject = "AboutGoalOfProject",
  SimpleTenses = "SimpleTenses",
  Prepositions = "Prepositions",
  Watch = "Watch",
  Articles = "Articles",
  DegreesOfComparison = "DegreesOfComparison",
  FamilySet = "FamilySet",
  RoutineSet = "RoutineSet",
  RecruitmentStudyWork = "RecruitmentStudyWork",
  TravelSet = "TravelSet",
  NatureSet = "NatureSet",
  UnderstandingBasicGrammar = "UnderstandingBasicGrammar",
  MasteringMainTopics = "MasteringMainTopics",
  UnderstandingBasicsOfLanguage = "UnderstandingBasicsOfLanguage",
  OurTextbook = "OurTextbook",
  TwelveBasicTimes = "TwelveBasicTimes",
  ModalVerbs = "ModalVerbs",
  ConditionalSentences1and2levels = "ConditionalSentences1and2levels",
  Gerund = "Gerund",
  PassiveVoice = "PassiveVoice",
  FoodAndHealthSet = "FoodAndHealthSet",
  TourismSet = "TourismSet",
  SocialNetworksSet = "SocialNetworksSet",
  BookMovieSet = "BookMovieSet",
  UnderstandingAndAbilityToUseGrammarForAdvancedStudents = "UnderstandingAndAbilityToUseGrammarForAdvancedStudents",
  HearingComprehension = "HearingComprehension",
  ConditionalSentencesAllLevels = "ConditionalSentencesAllLevels",
  TurnoversIwishIfOnly = "TurnoversIwishIfOnly",
  DirectAndIndirectSpeech = "DirectAndIndirectSpeech",
  ComplexObject = "ComplexObject",
  ComplexSubject = "ComplexSubject",
  BodyAndFeelingsSet = "BodyAndFeelingsSet",
  SetStory = "SetStory",
  EnvironmentSet = "EnvironmentSet",
  SocietyProblemSet = "SocietyProblemSet",
  MasteringTheMainTopics = "MasteringTheMainTopics",
  SoundsAndDiphthongs = "SoundsAndDiphthongs",
  ConjugationOfVerbs = "ConjugationOfVerbs",
  PrepositionsAndAdverbs = "PrepositionsAndAdverbs",
  VerbsWithPrefixes = "VerbsWithPrefixes",
  AcquaintanceSet = "AcquaintanceSet",
  HobbySet = "HobbySet",
  FriendshipSet = "FriendshipSet",
  HealthSet = "HealthSet",
  FutureTime = "FutureTime",
  Unions = "Unions",
  PronounDeclensions = "PronounDeclensions",
  PastTense = "PastTense",
  ConditionalClausesSuggestions = "ConditionalClausesSuggestions",
  AdverbialClausesOfTheCorollary = "AdverbialClausesOfTheCorollary",
  ZuinfinitivConstruction = "ZuinfinitivConstruction",
  RelativeClauses = "RelativeClauses",
  ArtSet = "ArtSet",
  SoundsAndTheirPronunciation = "SoundsAndTheirPronunciation",
  Childbirth = "Childbirth",
  PresentTense = "PresentTense",
  SetAboutMe = "SetAboutMe",
  PastTenses = "PastTenses",
  RelativePronouns = "RelativePronouns",
  PassiveFormOfTheVerb = "PassiveFormOfTheVerb",
  ConditionalMoods = "ConditionalMoods",
  AppearanceCharacter = "AppearanceCharacter",
  SportsSet = "SportsSet",
  ConversationOnSimpleTopics = "ConversationOnSimpleTopics",
  ReadingWithComprehension = "ReadingWithComprehension",
  PhoneCallWithTeacher2x = "PhoneCallWithTeacher2x",
  CheckingHomework = "CheckingHomework",
  ConversationClubs2x = "ConversationClubs2x",
  GrammarComprehensionForAdvanced = "GrammarComprehensionForAdvanced",
  ConfidentSpeaking = "ConfidentSpeaking",
  PerceptionOfInformationByEar = "PerceptionOfInformationByEar",
  WithTeacher = "WithTeacher",
  WithZlata = "WithZlata",
  GrammarLevelsA1A2B1B2 = "GrammarLevelsA1A2B1B2",
  Exercises = "Exercises",
  VideoMaterials = "VideoMaterials",
  ChatWithTeacher = "ChatWithTeacher",
  TwoLessonsWithZlata = "TwoLessonsWithZlata",
  ChatWithZlata = "ChatWithZlata",
  ContractOffer = "ContractOffer",
  PrivacyPolicy = "PrivacyPolicy",
  ShippingAndPayment = "ShippingAndPayment",
}

export type PosipilityProps = keyof typeof Props;

export enum LevelOfStudyEnum {
  A1A2 = "A1A2",
  B1 = "B1",
  B2 = "B2",
}

export enum LanguageOfStudyEnum {
  English = "English",
  French = "French",
  Deutsch = "Deutsch",
}

export enum FormatOfStudyEnum {
  Textbook = "Textbook",
  TutorialWithTeacher = "TutorialWithTeacher",
  TutorialWithZlata = "TutorialWithZlata",
}
